config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  get "/users/favorites/:id" => "users#favorites"
  get "/top" => "users#top"
  resources :posts do
    collection do
      post :confirm
    end
  end
  resources :favorites, only: [:create, :destroy]
  resources :tops
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :content, length: { in: 1..140 } 
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user

    mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_path, notice: "#{favorite.post.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to posts_path, notice: "#{favorite.post.user.name}さんの投稿のお気に入り解除しました"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update,:destroy]

  def index
     @posts = Post.all 
  end

  def new
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.new
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      NotificationMailer.notification_mail(@post).deliver  ##追記
      redirect_to controller: 'users', action: 'show', id:current_user.id, notice: "作成しました！"
    else
      # 入力フォームを再描画します。
      render 'new'
    end
  end
  
  def confirm
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    render :new if @post.invalid?
  end
  
  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      redirect_to controller: 'users', action: 'show', id:current_user.id, notice: "編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @post.destroy
    redirect_to controller: 'users', action: 'show', id:current_user.id, notice:"削除しました！"
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :content, :user_id, :image, :image_cache)
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
  def correct_user
     post = Post.find(params[:id])
     if current_user.id != post.user.id
       redirect_to root_path
     end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:show, :edit, :update]
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    # imageに指定がないとき、デフォルト画像を使う
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to("/users/#{@user.id}")
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
    
  end
  
  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
      redirect_to @user
      flash[:success] = "My Pageを更新しました" 
     else
      render'edit'
     end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def favorites
    @user = User.find(params[:id])
    @favorites_posts = @user.favorite_posts
    
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :image, :image_cache, :password,
                                 :password_confirmation)
  end
  
  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstagramClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/earlyaccess/notosansjapanese.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,900" rel="stylesheet">

  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <ul>
      <h2>InstagramClone</h2>
      <h3>Catch every world moment, and let's share it!</h3>
    <% if logged_in? %>
      <li><%= link_to "TOP", "/top" %>
      <li><%= link_to "View Posts", posts_path%>
      <li><%= link_to "New Post", new_post_path %>
      <li><%= link_to "My Favorites", "/users/favorites/#{current_user.id}" %>
      <li><%= link_to "My Page", "/users/#{current_user.id}"  %>      
      <li><%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <li><%= link_to "TOP", "/top" %></li>
      <li><%= link_to "Sign up", new_user_path %></li>
      <li><%= link_to "Login", new_session_path %></li>
    <% end %>
    </ul>
  </header>
  　<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %> 

<%= yield %>



</body>
</html>

app/views/posts/_form.html.erb
<div class="container">
<%= form_with(model: @post, local: true ,url: choose_new_or_edit ) do |form| %>  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="post_image">
    <%= image_tag(@post.image.url) if @post.image.url %>
    <%= form.file_field :image, id: :post_image, class: 'form_image'%>
  </div>
  <div class="post_title">
    <%= form.label :タイトル %>
    <%= form.text_field :title, class: 'form_title' %>
  </div>
  <div class="post_content">
    <%= form.label :本文 %>
    <%= form.text_field :content, class: 'form_content' %>
  </div>

  <%= form.submit :投稿する, class: 'btn btn-info' %>
<% end %>

<br><%= link_to "一覧画面にもどる", posts_path %>
</div>

app/views/posts/confirm.html.erb
<div class="container">
  <p>以下の内容で、送信する。</p>

  <%= form_with(model: @post, url: posts_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
　<%= form.hidden_field :image_cache %>
  <p>タイトル:<%= @post.title %></p>
  <p>本文:<%= @post.content %></p>
  <p>画像:<%= image_tag(@post.image) %></p>
  <%= form.submit  "登録する" %>
<% end %>

  <%= form_with(model: @post, url: new_post_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>
</div>

app/views/posts/edit.html.erb
 <h1>投稿を編集する</h1>

  <%= render 'form' %>

app/views/posts/index.html.erb
<div class="container">
  <ul class="row">
    <p>All Posts</p>
    <% @posts.each do |post| %>
    <li class="col-sm-6 col-md-6"><%= post.title %></li> 
    <li class="col-sm-6 col-md-4"><%= link_to 'show', post_path(post.id), class: 'btn btn-info' %></li> 
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
 <p>New Post</p>

  <%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">
  <p>Title: <%= @post.title %></p>
  <p><%= image_tag @post.image %></p>
  <p>Content: <%= @post.content %></p>
  <p>Posted by <%= @post.user.name %></p>
  <ul class="row">
  <% unless @post.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% end %>

  <% if @post.user_id == current_user.id %>
    <li class="col-sm-6 col-md-4"><%= link_to '編集', edit_post_path(@post.id), data: { confirm: '本当に編集していいですか？' }, class: 'btn btn-info' %>　　　<%= link_to '削除', post_path(@post.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-danger' %></li> 
    <% else %>　
  <% end %>
  <br><br>
  <%= link_to "戻る", :back %>
  </ul>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<p>ユーザー編集</p>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "") %> 件のエラーがあります。:</h2>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :プロフィール画像 %>
      <%= f.file_field :image, id: :user_image %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="container">
  <p>My Favorites</p>
  <p><%= notice %></p>
  <ul class="row">
    <% @favorites_posts.each do |favorite| %>
    <li class="col-sm-6 col-md-6"><%= favorite.title %></li> 
    <li class="col-sm-6 col-md-4"><%= link_to 'show', post_path(id: favorite.id), class: 'btn btn-info' %></li> 
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>New User</h1>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "件のエラー") %>が出ています。:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <%= form_with(model: @user, local: true) do |f| %>  
    <%= f.label :ユーザー名 %>
    <%= f.text_field :name %>

    <%= f.label :メールアドレス %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.label :Image %>
    <%= f.file_field :image, id: :user_image %>
    
    <%= f.submit "Create my account" %>
 <% end %>
 </div>

app/views/users/show.html.erb
<div class="container">
  <p>ユーザー名：<%= @user.name %></p>
  <p>メールアドレス：<%= @user.email %></p>
  <p><%= image_tag @user.image %><br>ユーザー画像</p>
<%= link_to '編集する', edit_user_path(current_user) %>
  <h4>My Posts</h4>
  <ul class="row">
    <% @user.posts.each do |post| %>
    <li class="col-sm-6 col-md-6"><%= post.title %></li> 
    <li class="col-sm-6 col-md-4"><%= link_to 'show', post_path(post.id), class: 'btn btn-info' %></li> 
    <% end %>
  </ul>
</div>

app/views/users/top.html.erb
<div class="about-background">
  <h1>Catch every world moment, and let's share it!</h1>
  <p>
      InstagramCloneで日常の瞬間をとらえた写真を簡単にシェアしよう。<br>
      世界中の面白いコンテンツを楽しむこともできます。<br>
      大事な瞬間から日常のあらゆる瞬間まで、自分を表現するいろいろなコンテンツをシェアしよう。
  </p>
</div>